#Category
CATEGORY_NAME_MIN_LENGTH = 3
CATEGORY_NAME_MAX_LENGTH = 50

#Product
PRODUCT_MIN_GRADE = 1
PRODUCT_MAX_GRADE = 5
PRODUCT_NAME_MIN_LENGTH = 3
PRODUCT_NAME_MAX_LENGTH = 100
PRODUCT_DESCRIPTION_MAX_LENGTH = 500
PRODUCT_IMAGE_URL_MAX_LENGTH = 200

#ProductList
PRODUCT_LIST_PAGE_NUMBER_DEFAULT = 1
PRODUCT_LIST_PAGE_SIZE_DEFAULT = 20
PRODUCT_LIST_PAGE_SIZE_MIN = 1
PRODUCT_LIST_PAGE_SIZE_MAX = 100

#User
USER_PASSWORD_MIN_LENGTH = 8
USER_ROLE_ADMIN = "admin"
USER_ROLE_SELLER = "seller"
USER_ROLE_BUYER = "buyer"